from typing import Protocol
from datetime import datetime

from app.schemas.calendar import CalendarCreateResult, ConnectionStatus, CalendarMetadata, CalendarEventRange


class CalendarProvider(Protocol):
    def get_connection_status(self) -> ConnectionStatus: ...
    def get_default_calendar(self) -> CalendarMetadata: ...
    def list_events(self, start: datetime, end: datetime) -> CalendarEventRange: ...
    def create_event(self, *, title: str, start: datetime, end: datetime,
                     location: str | None, transaction_id: str) -> CalendarCreateResult: ...
