"""task proposals audit table

Revision ID: 66405497a397
Revises: 4756c9756074
Create Date: 2026-08-11 00:14:49.584582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66405497a397'
down_revision: Union[str, Sequence[str], None] = '4756c9756074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_message_id', sa.Integer(), nullable=False),
    sa.Column('assistant_message_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('arguments_json', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_task_proposals_conversation_id'), 'task_proposals', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_task_proposals_id'), 'task_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_task_proposals_task_id'), 'task_proposals', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_proposals_task_id'), table_name='task_proposals')
    op.drop_index(op.f('ix_task_proposals_id'), table_name='task_proposals')
    op.drop_index(op.f('ix_task_proposals_conversation_id'), table_name='task_proposals')
    op.drop_table('task_proposals')
    # ### end Alembic commands ###
